### ISSUE TITLE
Map load is red

### ISSUE THREAD

**Issue by T0biii** [awlx/unifi_respondd#10]
@GoliathLabs:
Eine Sache, die ich noch nicht verstehe ist, warum die load von 0.1 im Meshviewer rot ist, statt grün wie bei den nicht unifi APs
Controller:
![image](https://user-images.githubusercontent.com/5702338/147880038-0eecd6f9-699a-4f75-afa6-e83db31ae704.png)
FFMUC Firmware:
![image](https://user-images.githubusercontent.com/5702338/147880054-bad53e7a-d9fb-4ee7-90ee-1c10938412b7.png)

**Comment by awlx** [comment]
Maybe a reference value is needed? Like `num_cpus` ?

**Comment by peterbaumert** [comment]
```return showBar(d.loadavg.toFixed(2), d.loadavg / (d.nproc || 1), d.loadavg >= d.nproc);```

maybe yes @awlx if d.nproc is 0 its always "warning"

**Comment by awlx** [comment]
Closed via #18
