### ISSUE TITLE
Add traffic statistics 

### ISSUE THREAD

**Issue by awlx** [awlx/unifi_respondd#4]
At the moment the traffic statistics are missing.

**Comment by T0biii** [comment]
for download:
![image](https://user-images.githubusercontent.com/5702338/147868505-f85d05c6-a398-4781-9d7f-74a452dbe3cc.png)
while download:
![image](https://user-images.githubusercontent.com/5702338/147868511-19635e01-76a1-4351-ada5-3c7f9631fe2f.png)
so maybe thats the right values for Traffic per AP?
```python
def get_traffic_for_ap(ap):
    tx_bytes = ap.get("tx_bytes-d", None)
    rx_bytes = ap.get("rx_bytes-d", None)
    return tx_bytes, rx_bytes
```

**Comment by awlx** [comment]
At the moment traffic is counted like this on the Grafana frontend:
```
SELECT non_negative_derivative(mean("traffic.forward.bytes"), 1s)  * 8 FROM "node" WHERE ("nodeid" =~ /^$nodeid$/) AND $timeFilter GROUP BY time($__interval) fill(null)
```

So it looks like we need a `total_bytes` value which is increasing all the time and not a momentary bandwidth.

**Comment by T0biii** [comment]
so maybe we want this values?
![image](https://user-images.githubusercontent.com/5702338/147876473-592e00af-2b5b-410c-8595-008c1a0404c4.png)

**Comment by awlx** [comment]
@T0biii yep, looks good :).

**Comment by awlx** [comment]
Closed via https://github.com/awlx/unifi_respondd/commit/5b710bb0a14e58888ae024e8f1993dd32d3051a4
